/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ad {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "startsAt")]
    pub starts_at: String,
    #[serde(rename = "place")]
    pub place: String,
    #[serde(rename = "priority")]
    pub priority: String,
    #[serde(rename = "ratio")]
    pub ratio: f64,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "imageUrl")]
    pub image_url: String,
    #[serde(rename = "memo")]
    pub memo: String,
    #[serde(rename = "dayOfWeek")]
    pub day_of_week: i32,
}

impl Ad {
    pub fn new(id: String, expires_at: String, starts_at: String, place: String, priority: String, ratio: f64, url: String, image_url: String, memo: String, day_of_week: i32) -> Ad {
        Ad {
            id,
            expires_at,
            starts_at,
            place,
            priority,
            ratio,
            url,
            image_url,
            memo,
            day_of_week,
        }
    }
}

