/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminGetIndexStats200ResponseInner {
    #[serde(rename = "tablename")]
    pub tablename: String,
    #[serde(rename = "indexname")]
    pub indexname: String,
}

impl AdminGetIndexStats200ResponseInner {
    pub fn new(tablename: String, indexname: String) -> AdminGetIndexStats200ResponseInner {
        AdminGetIndexStats200ResponseInner {
            tablename,
            indexname,
        }
    }
}

