/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAdListRequest {
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "sinceId", skip_serializing_if = "Option::is_none")]
    pub since_id: Option<String>,
    #[serde(rename = "untilId", skip_serializing_if = "Option::is_none")]
    pub until_id: Option<String>,
    #[serde(rename = "publishing", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub publishing: Option<Option<bool>>,
}

impl AdminAdListRequest {
    pub fn new() -> AdminAdListRequest {
        AdminAdListRequest {
            limit: None,
            since_id: None,
            until_id: None,
            publishing: None,
        }
    }
}

