/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminQueueStats200Response {
    #[serde(rename = "deliver")]
    pub deliver: Box<models::QueueCount>,
    #[serde(rename = "inbox")]
    pub inbox: Box<models::QueueCount>,
    #[serde(rename = "db")]
    pub db: Box<models::QueueCount>,
    #[serde(rename = "objectStorage")]
    pub object_storage: Box<models::QueueCount>,
}

impl AdminQueueStats200Response {
    pub fn new(deliver: models::QueueCount, inbox: models::QueueCount, db: models::QueueCount, object_storage: models::QueueCount) -> AdminQueueStats200Response {
        AdminQueueStats200Response {
            deliver: Box::new(deliver),
            inbox: Box::new(inbox),
            db: Box::new(db),
            object_storage: Box::new(object_storage),
        }
    }
}

