/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAdCreateRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "memo")]
    pub memo: String,
    #[serde(rename = "place")]
    pub place: String,
    #[serde(rename = "priority")]
    pub priority: String,
    #[serde(rename = "ratio")]
    pub ratio: i32,
    #[serde(rename = "expiresAt")]
    pub expires_at: i32,
    #[serde(rename = "startsAt")]
    pub starts_at: i32,
    #[serde(rename = "imageUrl")]
    pub image_url: String,
    #[serde(rename = "dayOfWeek")]
    pub day_of_week: i32,
}

impl AdminAdCreateRequest {
    pub fn new(url: String, memo: String, place: String, priority: String, ratio: i32, expires_at: i32, starts_at: i32, image_url: String, day_of_week: i32) -> AdminAdCreateRequest {
        AdminAdCreateRequest {
            url,
            memo,
            place,
            priority,
            ratio,
            expires_at,
            starts_at,
            image_url,
            day_of_week,
        }
    }
}

