/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRolesAssignRequest {
    #[serde(rename = "roleId")]
    pub role_id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<i32>>,
}

impl AdminRolesAssignRequest {
    pub fn new(role_id: String, user_id: String) -> AdminRolesAssignRequest {
        AdminRolesAssignRequest {
            role_id,
            user_id,
            expires_at: None,
        }
    }
}

