/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminShowUser200ResponseNotificationRecieveConfigNoteOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AdminShowUser200ResponseNotificationRecieveConfigNoteOneOf {
    pub fn new(r#type: Type) -> AdminShowUser200ResponseNotificationRecieveConfigNoteOneOf {
        AdminShowUser200ResponseNotificationRecieveConfigNoteOneOf {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "following")]
    Following,
    #[serde(rename = "follower")]
    Follower,
    #[serde(rename = "mutualFollow")]
    MutualFollow,
    #[serde(rename = "followingOrFollower")]
    FollowingOrFollower,
    #[serde(rename = "never")]
    Never,
}

impl Default for Type {
    fn default() -> Type {
        Self::All
    }
}

