/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAnnouncementsCreate200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt", deserialize_with = "Option::deserialize")]
    pub updated_at: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "imageUrl", deserialize_with = "Option::deserialize")]
    pub image_url: Option<String>,
}

impl AdminAnnouncementsCreate200Response {
    pub fn new(id: String, created_at: String, updated_at: Option<String>, title: String, text: String, image_url: Option<String>) -> AdminAnnouncementsCreate200Response {
        AdminAnnouncementsCreate200Response {
            id,
            created_at,
            updated_at,
            title,
            text,
            image_url,
        }
    }
}

