/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminShowUser200ResponseRoleAssignsInner {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    #[serde(rename = "roleId")]
    pub role_id: String,
}

impl AdminShowUser200ResponseRoleAssignsInner {
    pub fn new(created_at: String, expires_at: Option<String>, role_id: String) -> AdminShowUser200ResponseRoleAssignsInner {
        AdminShowUser200ResponseRoleAssignsInner {
            created_at,
            expires_at,
            role_id,
        }
    }
}

