/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRolesUsers200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "user")]
    pub user: Box<models::UserDetailed>,
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
}

impl AdminRolesUsers200ResponseInner {
    pub fn new(id: String, created_at: String, user: models::UserDetailed, expires_at: Option<String>) -> AdminRolesUsers200ResponseInner {
        AdminRolesUsers200ResponseInner {
            id,
            created_at,
            user: Box::new(user),
            expires_at,
        }
    }
}

