/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminQueuePromoteRequest {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AdminQueuePromoteRequest {
    pub fn new(r#type: Type) -> AdminQueuePromoteRequest {
        AdminQueuePromoteRequest {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "deliver")]
    Deliver,
    #[serde(rename = "inbox")]
    Inbox,
}

impl Default for Type {
    fn default() -> Type {
        Self::Deliver
    }
}

