/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnouncementsShowRequest {
    #[serde(rename = "announcementId")]
    pub announcement_id: String,
}

impl AnnouncementsShowRequest {
    pub fn new(announcement_id: String) -> AnnouncementsShowRequest {
        AnnouncementsShowRequest {
            announcement_id,
        }
    }
}

