/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AntennasDeleteRequest {
    #[serde(rename = "antennaId")]
    pub antenna_id: String,
}

impl AntennasDeleteRequest {
    pub fn new(antenna_id: String) -> AntennasDeleteRequest {
        AntennasDeleteRequest {
            antenna_id,
        }
    }
}

