/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AntennasCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "src")]
    pub src: Src,
    #[serde(rename = "userListId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_list_id: Option<Option<String>>,
    #[serde(rename = "keywords")]
    pub keywords: Vec<Vec<String>>,
    #[serde(rename = "excludeKeywords")]
    pub exclude_keywords: Vec<Vec<String>>,
    #[serde(rename = "users")]
    pub users: Vec<String>,
    #[serde(rename = "caseSensitive")]
    pub case_sensitive: bool,
    #[serde(rename = "localOnly", skip_serializing_if = "Option::is_none")]
    pub local_only: Option<bool>,
    #[serde(rename = "excludeBots", skip_serializing_if = "Option::is_none")]
    pub exclude_bots: Option<bool>,
    #[serde(rename = "withReplies")]
    pub with_replies: bool,
    #[serde(rename = "withFile")]
    pub with_file: bool,
}

impl AntennasCreateRequest {
    pub fn new(name: String, src: Src, keywords: Vec<Vec<String>>, exclude_keywords: Vec<Vec<String>>, users: Vec<String>, case_sensitive: bool, with_replies: bool, with_file: bool) -> AntennasCreateRequest {
        AntennasCreateRequest {
            name,
            src,
            user_list_id: None,
            keywords,
            exclude_keywords,
            users,
            case_sensitive,
            local_only: None,
            exclude_bots: None,
            with_replies,
            with_file,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Src {
    #[serde(rename = "home")]
    Home,
    #[serde(rename = "all")]
    All,
    #[serde(rename = "users")]
    Users,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "users_blacklist")]
    UsersBlacklist,
}

impl Default for Src {
    fn default() -> Src {
        Self::Home
    }
}

