/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppShowRequest {
    #[serde(rename = "appId")]
    pub app_id: String,
}

impl AppShowRequest {
    pub fn new(app_id: String) -> AppShowRequest {
        AppShowRequest {
            app_id,
        }
    }
}

