/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSessionUserkey200Response {
    #[serde(rename = "accessToken")]
    pub access_token: String,
    #[serde(rename = "user")]
    pub user: models::UserDetailedNotMe,
}

impl AuthSessionUserkey200Response {
    pub fn new(access_token: String, user: models::UserDetailedNotMe) -> AuthSessionUserkey200Response {
        AuthSessionUserkey200Response {
            access_token,
            user,
        }
    }
}

