/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSessionGenerate200Response {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl AuthSessionGenerate200Response {
    pub fn new(token: String, url: String) -> AuthSessionGenerate200Response {
        AuthSessionGenerate200Response {
            token,
            url,
        }
    }
}

