/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelsUpdateRequest {
    #[serde(rename = "channelId")]
    pub channel_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "bannerId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banner_id: Option<Option<String>>,
    #[serde(rename = "isArchived", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<Option<bool>>,
    #[serde(rename = "pinnedNoteIds", skip_serializing_if = "Option::is_none")]
    pub pinned_note_ids: Option<Vec<String>>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "isSensitive", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_sensitive: Option<Option<bool>>,
    #[serde(rename = "allowRenoteToExternal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_renote_to_external: Option<Option<bool>>,
}

impl ChannelsUpdateRequest {
    pub fn new(channel_id: String) -> ChannelsUpdateRequest {
        ChannelsUpdateRequest {
            channel_id,
            name: None,
            description: None,
            banner_id: None,
            is_archived: None,
            pinned_note_ids: None,
            color: None,
            is_sensitive: None,
            allow_renote_to_external: None,
        }
    }
}

