/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartsInstance200ResponseNotesDiffs {
    #[serde(rename = "normal")]
    pub normal: Vec<f64>,
    #[serde(rename = "reply")]
    pub reply: Vec<f64>,
    #[serde(rename = "renote")]
    pub renote: Vec<f64>,
    #[serde(rename = "withFile")]
    pub with_file: Vec<f64>,
}

impl ChartsInstance200ResponseNotesDiffs {
    pub fn new(normal: Vec<f64>, reply: Vec<f64>, renote: Vec<f64>, with_file: Vec<f64>) -> ChartsInstance200ResponseNotesDiffs {
        ChartsInstance200ResponseNotesDiffs {
            normal,
            reply,
            renote,
            with_file,
        }
    }
}

