/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartsInstance200ResponseUsers {
    #[serde(rename = "total")]
    pub total: Vec<f64>,
    #[serde(rename = "inc")]
    pub inc: Vec<f64>,
    #[serde(rename = "dec")]
    pub dec: Vec<f64>,
}

impl ChartsInstance200ResponseUsers {
    pub fn new(total: Vec<f64>, inc: Vec<f64>, dec: Vec<f64>) -> ChartsInstance200ResponseUsers {
        ChartsInstance200ResponseUsers {
            total,
            inc,
            dec,
        }
    }
}

