/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartsUserReactions200ResponseLocal {
    #[serde(rename = "count")]
    pub count: Vec<f64>,
}

impl ChartsUserReactions200ResponseLocal {
    pub fn new(count: Vec<f64>) -> ChartsUserReactions200ResponseLocal {
        ChartsUserReactions200ResponseLocal {
            count,
        }
    }
}

