/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChartsApRequest200Response {
    #[serde(rename = "deliverFailed")]
    pub deliver_failed: Vec<f64>,
    #[serde(rename = "deliverSucceeded")]
    pub deliver_succeeded: Vec<f64>,
    #[serde(rename = "inboxReceived")]
    pub inbox_received: Vec<f64>,
}

impl ChartsApRequest200Response {
    pub fn new(deliver_failed: Vec<f64>, deliver_succeeded: Vec<f64>, inbox_received: Vec<f64>) -> ChartsApRequest200Response {
        ChartsApRequest200Response {
            deliver_failed,
            deliver_succeeded,
            inbox_received,
        }
    }
}

