/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DriveFilesUpdateRequest {
    #[serde(rename = "fileId")]
    pub file_id: String,
    #[serde(rename = "folderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<Option<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isSensitive", skip_serializing_if = "Option::is_none")]
    pub is_sensitive: Option<bool>,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
}

impl DriveFilesUpdateRequest {
    pub fn new(file_id: String) -> DriveFilesUpdateRequest {
        DriveFilesUpdateRequest {
            file_id,
            folder_id: None,
            name: None,
            is_sensitive: None,
            comment: None,
        }
    }
}

