/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Drive200Response {
    #[serde(rename = "capacity")]
    pub capacity: f64,
    #[serde(rename = "usage")]
    pub usage: f64,
}

impl Drive200Response {
    pub fn new(capacity: f64, usage: f64) -> Drive200Response {
        Drive200Response {
            capacity,
            usage,
        }
    }
}

