/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint200ResponseParamsInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Endpoint200ResponseParamsInner {
    pub fn new(name: String, r#type: String) -> Endpoint200ResponseParamsInner {
        Endpoint200ResponseParamsInner {
            name,
            r#type,
        }
    }
}

