/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint200Response {
    #[serde(rename = "params")]
    pub params: Vec<models::Endpoint200ResponseParamsInner>,
}

impl Endpoint200Response {
    pub fn new(params: Vec<models::Endpoint200ResponseParamsInner>) -> Endpoint200Response {
        Endpoint200Response {
            params,
        }
    }
}

