/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FederationStats200Response {
    #[serde(rename = "topSubInstances")]
    pub top_sub_instances: Vec<models::FederationInstance>,
    #[serde(rename = "otherFollowersCount")]
    pub other_followers_count: f64,
    #[serde(rename = "topPubInstances")]
    pub top_pub_instances: Vec<models::FederationInstance>,
    #[serde(rename = "otherFollowingCount")]
    pub other_following_count: f64,
}

impl FederationStats200Response {
    pub fn new(top_sub_instances: Vec<models::FederationInstance>, other_followers_count: f64, top_pub_instances: Vec<models::FederationInstance>, other_following_count: f64) -> FederationStats200Response {
        FederationStats200Response {
            top_sub_instances,
            other_followers_count,
            top_pub_instances,
            other_following_count,
        }
    }
}

