/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchExternalResources200Response {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "data")]
    pub data: String,
}

impl FetchExternalResources200Response {
    pub fn new(r#type: String, data: String) -> FetchExternalResources200Response {
        FetchExternalResources200Response {
            r#type,
            data,
        }
    }
}

