/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchExternalResourcesRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "hash")]
    pub hash: String,
}

impl FetchExternalResourcesRequest {
    pub fn new(url: String, hash: String) -> FetchExternalResourcesRequest {
        FetchExternalResourcesRequest {
            url,
            hash,
        }
    }
}

