/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashtagsUsersRequest {
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "sort")]
    pub sort: Sort,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Origin>,
}

impl HashtagsUsersRequest {
    pub fn new(tag: String, sort: Sort) -> HashtagsUsersRequest {
        HashtagsUsersRequest {
            tag,
            limit: None,
            sort,
            state: None,
            origin: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sort {
    #[serde(rename = "+follower")]
    PlusFollower,
    #[serde(rename = "-follower")]
    Follower,
    #[serde(rename = "+createdAt")]
    PlusCreatedAt,
    #[serde(rename = "-createdAt")]
    CreatedAt,
    #[serde(rename = "+updatedAt")]
    PlusUpdatedAt,
    #[serde(rename = "-updatedAt")]
    UpdatedAt,
}

impl Default for Sort {
    fn default() -> Sort {
        Self::PlusFollower
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "alive")]
    Alive,
}

impl Default for State {
    fn default() -> State {
        Self::All
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Origin {
    #[serde(rename = "combined")]
    Combined,
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "remote")]
    Remote,
}

impl Default for Origin {
    fn default() -> Origin {
        Self::Combined
    }
}

