/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashtagsTrend200ResponseInner {
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "chart")]
    pub chart: Vec<f64>,
    #[serde(rename = "usersCount")]
    pub users_count: f64,
}

impl HashtagsTrend200ResponseInner {
    pub fn new(tag: String, chart: Vec<f64>, users_count: f64) -> HashtagsTrend200ResponseInner {
        HashtagsTrend200ResponseInner {
            tag,
            chart,
            users_count,
        }
    }
}

