/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashtagsListRequest {
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "attachedToUserOnly", skip_serializing_if = "Option::is_none")]
    pub attached_to_user_only: Option<bool>,
    #[serde(rename = "attachedToLocalUserOnly", skip_serializing_if = "Option::is_none")]
    pub attached_to_local_user_only: Option<bool>,
    #[serde(rename = "attachedToRemoteUserOnly", skip_serializing_if = "Option::is_none")]
    pub attached_to_remote_user_only: Option<bool>,
    #[serde(rename = "sort")]
    pub sort: Sort,
}

impl HashtagsListRequest {
    pub fn new(sort: Sort) -> HashtagsListRequest {
        HashtagsListRequest {
            limit: None,
            attached_to_user_only: None,
            attached_to_local_user_only: None,
            attached_to_remote_user_only: None,
            sort,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sort {
    #[serde(rename = "+mentionedUsers")]
    PlusMentionedUsers,
    #[serde(rename = "-mentionedUsers")]
    MentionedUsers,
    #[serde(rename = "+mentionedLocalUsers")]
    PlusMentionedLocalUsers,
    #[serde(rename = "-mentionedLocalUsers")]
    MentionedLocalUsers,
    #[serde(rename = "+mentionedRemoteUsers")]
    PlusMentionedRemoteUsers,
    #[serde(rename = "-mentionedRemoteUsers")]
    MentionedRemoteUsers,
    #[serde(rename = "+attachedUsers")]
    PlusAttachedUsers,
    #[serde(rename = "-attachedUsers")]
    AttachedUsers,
    #[serde(rename = "+attachedLocalUsers")]
    PlusAttachedLocalUsers,
    #[serde(rename = "-attachedLocalUsers")]
    AttachedLocalUsers,
    #[serde(rename = "+attachedRemoteUsers")]
    PlusAttachedRemoteUsers,
    #[serde(rename = "-attachedRemoteUsers")]
    AttachedRemoteUsers,
}

impl Default for Sort {
    fn default() -> Sort {
        Self::PlusMentionedUsers
    }
}

