/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct I2faRemoveKeyRequest {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token: Option<Option<String>>,
    #[serde(rename = "credentialId")]
    pub credential_id: String,
}

impl I2faRemoveKeyRequest {
    pub fn new(password: String, credential_id: String) -> I2faRemoveKeyRequest {
        I2faRemoveKeyRequest {
            password,
            token: None,
            credential_id,
        }
    }
}

