/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct I2faRegister200Response {
    #[serde(rename = "qr")]
    pub qr: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "issuer")]
    pub issuer: String,
}

impl I2faRegister200Response {
    pub fn new(qr: String, url: String, secret: String, label: String, issuer: String) -> I2faRegister200Response {
        I2faRegister200Response {
            qr,
            url,
            secret,
            label,
            issuer,
        }
    }
}

