/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IUpdateRequestAvatarDecorationsInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "angle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub angle: Option<Option<f64>>,
    #[serde(rename = "flipH", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flip_h: Option<Option<bool>>,
    #[serde(rename = "offsetX", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offset_x: Option<Option<f64>>,
    #[serde(rename = "offsetY", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offset_y: Option<Option<f64>>,
}

impl IUpdateRequestAvatarDecorationsInner {
    pub fn new(id: String) -> IUpdateRequestAvatarDecorationsInner {
        IUpdateRequestAvatarDecorationsInner {
            id,
            angle: None,
            flip_h: None,
            offset_x: None,
            offset_y: None,
        }
    }
}

