/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IRegistryGetDetail200Response {
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl IRegistryGetDetail200Response {
    pub fn new(updated_at: String, value: Option<serde_json::Value>) -> IRegistryGetDetail200Response {
        IRegistryGetDetail200Response {
            updated_at,
            value,
        }
    }
}

