/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IRegistryScopesWithDomain200ResponseInner {
    #[serde(rename = "scopes")]
    pub scopes: Vec<Vec<String>>,
    #[serde(rename = "domain", deserialize_with = "Option::deserialize")]
    pub domain: Option<String>,
}

impl IRegistryScopesWithDomain200ResponseInner {
    pub fn new(scopes: Vec<Vec<String>>, domain: Option<String>) -> IRegistryScopesWithDomain200ResponseInner {
        IRegistryScopesWithDomain200ResponseInner {
            scopes,
            domain,
        }
    }
}

