/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct I2faRegisterKey200ResponseExtensions {
    #[serde(rename = "appid", deserialize_with = "Option::deserialize")]
    pub appid: Option<String>,
    #[serde(rename = "credProps", deserialize_with = "Option::deserialize")]
    pub cred_props: Option<bool>,
    #[serde(rename = "hmacCreateSecret", deserialize_with = "Option::deserialize")]
    pub hmac_create_secret: Option<bool>,
}

impl I2faRegisterKey200ResponseExtensions {
    pub fn new(appid: Option<String>, cred_props: Option<bool>, hmac_create_secret: Option<bool>) -> I2faRegisterKey200ResponseExtensions {
        I2faRegisterKey200ResponseExtensions {
            appid,
            cred_props,
            hmac_create_secret,
        }
    }
}

