/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IRegistrySetRequest {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "scope")]
    pub scope: Vec<String>,
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
}

impl IRegistrySetRequest {
    pub fn new(key: String, value: Option<serde_json::Value>, scope: Vec<String>) -> IRegistrySetRequest {
        IRegistrySetRequest {
            key,
            value,
            scope,
            domain: None,
        }
    }
}

