/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IUpdateRequestMutedWordsInner {
    Array(Vec<String>),
    String(String),
}

impl Default for IUpdateRequestMutedWordsInner {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}

