/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeDetailedOnlySecurityKeysListInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "lastUsed")]
    pub last_used: String,
}

impl MeDetailedOnlySecurityKeysListInner {
    pub fn new(id: String, name: String, last_used: String) -> MeDetailedOnlySecurityKeysListInner {
        MeDetailedOnlySecurityKeysListInner {
            id,
            name,
            last_used,
        }
    }
}

