/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaDetailed {
    #[serde(rename = "maintainerName")]
    pub maintainer_name: String,
    #[serde(rename = "maintainerEmail")]
    pub maintainer_email: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "providesTarball")]
    pub provides_tarball: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "shortName")]
    pub short_name: String,
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "langs")]
    pub langs: Vec<String>,
    #[serde(rename = "tosUrl")]
    pub tos_url: String,
    #[serde(rename = "repositoryUrl")]
    pub repository_url: String,
    #[serde(rename = "feedbackUrl")]
    pub feedback_url: String,
    #[serde(rename = "defaultDarkTheme")]
    pub default_dark_theme: String,
    #[serde(rename = "defaultLightTheme")]
    pub default_light_theme: String,
    #[serde(rename = "disableRegistration")]
    pub disable_registration: bool,
    #[serde(rename = "emailRequiredForSignup")]
    pub email_required_for_signup: bool,
    #[serde(rename = "enableHcaptcha")]
    pub enable_hcaptcha: bool,
    #[serde(rename = "hcaptchaSiteKey")]
    pub hcaptcha_site_key: String,
    #[serde(rename = "enableMcaptcha")]
    pub enable_mcaptcha: bool,
    #[serde(rename = "mcaptchaSiteKey")]
    pub mcaptcha_site_key: String,
    #[serde(rename = "mcaptchaInstanceUrl")]
    pub mcaptcha_instance_url: String,
    #[serde(rename = "enableRecaptcha")]
    pub enable_recaptcha: bool,
    #[serde(rename = "recaptchaSiteKey")]
    pub recaptcha_site_key: String,
    #[serde(rename = "enableTurnstile")]
    pub enable_turnstile: bool,
    #[serde(rename = "turnstileSiteKey")]
    pub turnstile_site_key: String,
    #[serde(rename = "swPublickey")]
    pub sw_publickey: String,
    #[serde(rename = "mascotImageUrl")]
    pub mascot_image_url: String,
    #[serde(rename = "bannerUrl")]
    pub banner_url: String,
    #[serde(rename = "serverErrorImageUrl")]
    pub server_error_image_url: String,
    #[serde(rename = "infoImageUrl")]
    pub info_image_url: String,
    #[serde(rename = "notFoundImageUrl")]
    pub not_found_image_url: String,
    #[serde(rename = "iconUrl")]
    pub icon_url: String,
    #[serde(rename = "maxNoteTextLength")]
    pub max_note_text_length: f64,
    #[serde(rename = "ads")]
    pub ads: Vec<models::MetaLiteAdsInner>,
    #[serde(rename = "notesPerOneAd")]
    pub notes_per_one_ad: f64,
    #[serde(rename = "enableEmail")]
    pub enable_email: bool,
    #[serde(rename = "enableServiceWorker")]
    pub enable_service_worker: bool,
    #[serde(rename = "translatorAvailable")]
    pub translator_available: bool,
    #[serde(rename = "mediaProxy")]
    pub media_proxy: String,
    #[serde(rename = "enableUrlPreview")]
    pub enable_url_preview: bool,
    #[serde(rename = "backgroundImageUrl")]
    pub background_image_url: String,
    #[serde(rename = "impressumUrl")]
    pub impressum_url: String,
    #[serde(rename = "logoImageUrl")]
    pub logo_image_url: String,
    #[serde(rename = "privacyPolicyUrl")]
    pub privacy_policy_url: String,
    #[serde(rename = "inquiryUrl")]
    pub inquiry_url: String,
    #[serde(rename = "serverRules")]
    pub server_rules: Vec<String>,
    #[serde(rename = "themeColor")]
    pub theme_color: String,
    #[serde(rename = "policies")]
    pub policies: models::RolePolicies,
    #[serde(rename = "noteSearchableScope")]
    pub note_searchable_scope: NoteSearchableScope,
    #[serde(rename = "maxFileSize")]
    pub max_file_size: f64,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<models::MetaDetailedOnlyFeatures>>,
    #[serde(rename = "proxyAccountName")]
    pub proxy_account_name: String,
    #[serde(rename = "requireSetup")]
    pub require_setup: bool,
    #[serde(rename = "cacheRemoteFiles")]
    pub cache_remote_files: bool,
    #[serde(rename = "cacheRemoteSensitiveFiles")]
    pub cache_remote_sensitive_files: bool,
}

impl MetaDetailed {
    pub fn new(maintainer_name: String, maintainer_email: String, version: String, provides_tarball: bool, name: String, short_name: String, uri: String, description: String, langs: Vec<String>, tos_url: String, repository_url: String, feedback_url: String, default_dark_theme: String, default_light_theme: String, disable_registration: bool, email_required_for_signup: bool, enable_hcaptcha: bool, hcaptcha_site_key: String, enable_mcaptcha: bool, mcaptcha_site_key: String, mcaptcha_instance_url: String, enable_recaptcha: bool, recaptcha_site_key: String, enable_turnstile: bool, turnstile_site_key: String, sw_publickey: String, mascot_image_url: String, banner_url: String, server_error_image_url: String, info_image_url: String, not_found_image_url: String, icon_url: String, max_note_text_length: f64, ads: Vec<models::MetaLiteAdsInner>, notes_per_one_ad: f64, enable_email: bool, enable_service_worker: bool, translator_available: bool, media_proxy: String, enable_url_preview: bool, background_image_url: String, impressum_url: String, logo_image_url: String, privacy_policy_url: String, inquiry_url: String, server_rules: Vec<String>, theme_color: String, policies: models::RolePolicies, note_searchable_scope: NoteSearchableScope, max_file_size: f64, proxy_account_name: String, require_setup: bool, cache_remote_files: bool, cache_remote_sensitive_files: bool) -> MetaDetailed {
        MetaDetailed {
            maintainer_name,
            maintainer_email,
            version,
            provides_tarball,
            name,
            short_name,
            uri,
            description,
            langs,
            tos_url,
            repository_url,
            feedback_url,
            default_dark_theme,
            default_light_theme,
            disable_registration,
            email_required_for_signup,
            enable_hcaptcha,
            hcaptcha_site_key,
            enable_mcaptcha,
            mcaptcha_site_key,
            mcaptcha_instance_url,
            enable_recaptcha,
            recaptcha_site_key,
            enable_turnstile,
            turnstile_site_key,
            sw_publickey,
            mascot_image_url,
            banner_url,
            server_error_image_url,
            info_image_url,
            not_found_image_url,
            icon_url,
            max_note_text_length,
            ads,
            notes_per_one_ad,
            enable_email,
            enable_service_worker,
            translator_available,
            media_proxy,
            enable_url_preview,
            background_image_url,
            impressum_url,
            logo_image_url,
            privacy_policy_url,
            inquiry_url,
            server_rules,
            theme_color,
            policies,
            note_searchable_scope,
            max_file_size,
            features: None,
            proxy_account_name,
            require_setup,
            cache_remote_files,
            cache_remote_sensitive_files,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NoteSearchableScope {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "global")]
    Global,
}

impl Default for NoteSearchableScope {
    fn default() -> NoteSearchableScope {
        Self::Local
    }
}

