/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaDetailedOnlyFeatures {
    #[serde(rename = "registration")]
    pub registration: bool,
    #[serde(rename = "emailRequiredForSignup")]
    pub email_required_for_signup: bool,
    #[serde(rename = "localTimeline")]
    pub local_timeline: bool,
    #[serde(rename = "globalTimeline")]
    pub global_timeline: bool,
    #[serde(rename = "hcaptcha")]
    pub hcaptcha: bool,
    #[serde(rename = "turnstile")]
    pub turnstile: bool,
    #[serde(rename = "recaptcha")]
    pub recaptcha: bool,
    #[serde(rename = "objectStorage")]
    pub object_storage: bool,
    #[serde(rename = "serviceWorker")]
    pub service_worker: bool,
    #[serde(rename = "miauth", skip_serializing_if = "Option::is_none")]
    pub miauth: Option<bool>,
}

impl MetaDetailedOnlyFeatures {
    pub fn new(registration: bool, email_required_for_signup: bool, local_timeline: bool, global_timeline: bool, hcaptcha: bool, turnstile: bool, recaptcha: bool, object_storage: bool, service_worker: bool) -> MetaDetailedOnlyFeatures {
        MetaDetailedOnlyFeatures {
            registration,
            email_required_for_signup,
            local_timeline,
            global_timeline,
            hcaptcha,
            turnstile,
            recaptcha,
            object_storage,
            service_worker,
            miauth: None,
        }
    }
}

