/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MiauthGenTokenRequest {
    #[serde(rename = "session", deserialize_with = "Option::deserialize")]
    pub session: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "iconUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<Option<String>>,
    #[serde(rename = "permission")]
    pub permission: Vec<String>,
}

impl MiauthGenTokenRequest {
    pub fn new(session: Option<String>, permission: Vec<String>) -> MiauthGenTokenRequest {
        MiauthGenTokenRequest {
            session,
            name: None,
            description: None,
            icon_url: None,
            permission,
        }
    }
}

