/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MuteCreateRequest {
    #[serde(rename = "userId")]
    pub user_id: String,
    /// A Unix Epoch timestamp that must lie in the future. `null` means an indefinite mute.
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<i32>>,
}

impl MuteCreateRequest {
    pub fn new(user_id: String) -> MuteCreateRequest {
        MuteCreateRequest {
            user_id,
            expires_at: None,
        }
    }
}

