/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Muting {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "expiresAt", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    #[serde(rename = "muteeId")]
    pub mutee_id: String,
    #[serde(rename = "mutee")]
    pub mutee: models::UserDetailedNotMe,
}

impl Muting {
    pub fn new(id: String, created_at: String, expires_at: Option<String>, mutee_id: String, mutee: models::UserDetailedNotMe) -> Muting {
        Muting {
            id,
            created_at,
            expires_at,
            mutee_id,
            mutee,
        }
    }
}

