/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotesCreate200Response {
    #[serde(rename = "createdNote")]
    pub created_note: models::Note,
}

impl NotesCreate200Response {
    pub fn new(created_note: models::Note) -> NotesCreate200Response {
        NotesCreate200Response {
            created_note,
        }
    }
}

