/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoteFavorite {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "note")]
    pub note: models::Note,
    #[serde(rename = "noteId")]
    pub note_id: String,
}

impl NoteFavorite {
    pub fn new(id: String, created_at: String, note: models::Note, note_id: String) -> NoteFavorite {
        NoteFavorite {
            id,
            created_at,
            note,
            note_id,
        }
    }
}

