/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationOneOf13 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "note")]
    pub note: models::Note,
    #[serde(rename = "reactions")]
    pub reactions: Vec<models::NotificationOneOf13ReactionsInner>,
}

impl NotificationOneOf13 {
    pub fn new(id: String, created_at: String, r#type: Type, note: models::Note, reactions: Vec<models::NotificationOneOf13ReactionsInner>) -> NotificationOneOf13 {
        NotificationOneOf13 {
            id,
            created_at,
            r#type,
            note,
            reactions,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "reaction:grouped")]
    ReactionColonGrouped,
}

impl Default for Type {
    fn default() -> Type {
        Self::ReactionColonGrouped
    }
}

