/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageBlockOneOf1 {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "children")]
    pub children: Vec<models::PageBlock>,
}

impl PageBlockOneOf1 {
    pub fn new(id: String, r#type: Type, title: String, children: Vec<models::PageBlock>) -> PageBlockOneOf1 {
        PageBlockOneOf1 {
            id,
            r#type,
            title,
            children,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "section")]
    Section,
}

impl Default for Type {
    fn default() -> Type {
        Self::Section
    }
}

