/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagesCreateRequest {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Option<String>>,
    #[serde(rename = "content")]
    pub content: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "variables")]
    pub variables: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "script")]
    pub script: String,
    #[serde(rename = "eyeCatchingImageId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub eye_catching_image_id: Option<Option<String>>,
    #[serde(rename = "font", skip_serializing_if = "Option::is_none")]
    pub font: Option<Font>,
    #[serde(rename = "alignCenter", skip_serializing_if = "Option::is_none")]
    pub align_center: Option<bool>,
    #[serde(rename = "hideTitleWhenPinned", skip_serializing_if = "Option::is_none")]
    pub hide_title_when_pinned: Option<bool>,
}

impl PagesCreateRequest {
    pub fn new(title: String, name: String, content: Vec<std::collections::HashMap<String, serde_json::Value>>, variables: Vec<std::collections::HashMap<String, serde_json::Value>>, script: String) -> PagesCreateRequest {
        PagesCreateRequest {
            title,
            name,
            summary: None,
            content,
            variables,
            script,
            eye_catching_image_id: None,
            font: None,
            align_center: None,
            hide_title_when_pinned: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Font {
    #[serde(rename = "serif")]
    Serif,
    #[serde(rename = "sans-serif")]
    SansSerif,
}

impl Default for Font {
    fn default() -> Font {
        Self::Serif
    }
}

