/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ping200Response {
    #[serde(rename = "pong")]
    pub pong: f64,
}

impl Ping200Response {
    pub fn new(pong: f64) -> Ping200Response {
        Ping200Response {
            pong,
        }
    }
}

