/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Retention200ResponseInner {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "users")]
    pub users: f64,
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, models::Retention200ResponseInnerDataValue>,
}

impl Retention200ResponseInner {
    pub fn new(created_at: String, users: f64, data: std::collections::HashMap<String, models::Retention200ResponseInnerDataValue>) -> Retention200ResponseInner {
        Retention200ResponseInner {
            created_at,
            users,
            data,
        }
    }
}

