/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReversiVerifyRequest {
    #[serde(rename = "gameId")]
    pub game_id: String,
    #[serde(rename = "crc32")]
    pub crc32: String,
}

impl ReversiVerifyRequest {
    pub fn new(game_id: String, crc32: String) -> ReversiVerifyRequest {
        ReversiVerifyRequest {
            game_id,
            crc32,
        }
    }
}

