/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleCondFormulaValueIsLocalOrRemote {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RoleCondFormulaValueIsLocalOrRemote {
    pub fn new(id: String, r#type: Type) -> RoleCondFormulaValueIsLocalOrRemote {
        RoleCondFormulaValueIsLocalOrRemote {
            id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "isLocal")]
    IsLocal,
    #[serde(rename = "isRemote")]
    IsRemote,
}

impl Default for Type {
    fn default() -> Type {
        Self::IsLocal
    }
}

