/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolePolicies {
    #[serde(rename = "gtlAvailable")]
    pub gtl_available: bool,
    #[serde(rename = "ltlAvailable")]
    pub ltl_available: bool,
    #[serde(rename = "canPublicNote")]
    pub can_public_note: bool,
    #[serde(rename = "mentionLimit")]
    pub mention_limit: i32,
    #[serde(rename = "canInvite")]
    pub can_invite: bool,
    #[serde(rename = "inviteLimit")]
    pub invite_limit: i32,
    #[serde(rename = "inviteLimitCycle")]
    pub invite_limit_cycle: i32,
    #[serde(rename = "inviteExpirationTime")]
    pub invite_expiration_time: i32,
    #[serde(rename = "canManageCustomEmojis")]
    pub can_manage_custom_emojis: bool,
    #[serde(rename = "canManageAvatarDecorations")]
    pub can_manage_avatar_decorations: bool,
    #[serde(rename = "canSearchNotes")]
    pub can_search_notes: bool,
    #[serde(rename = "canUseTranslator")]
    pub can_use_translator: bool,
    #[serde(rename = "canHideAds")]
    pub can_hide_ads: bool,
    #[serde(rename = "driveCapacityMb")]
    pub drive_capacity_mb: i32,
    #[serde(rename = "alwaysMarkNsfw")]
    pub always_mark_nsfw: bool,
    #[serde(rename = "canUpdateBioMedia")]
    pub can_update_bio_media: bool,
    #[serde(rename = "pinLimit")]
    pub pin_limit: i32,
    #[serde(rename = "antennaLimit")]
    pub antenna_limit: i32,
    #[serde(rename = "wordMuteLimit")]
    pub word_mute_limit: i32,
    #[serde(rename = "webhookLimit")]
    pub webhook_limit: i32,
    #[serde(rename = "clipLimit")]
    pub clip_limit: i32,
    #[serde(rename = "noteEachClipsLimit")]
    pub note_each_clips_limit: i32,
    #[serde(rename = "userListLimit")]
    pub user_list_limit: i32,
    #[serde(rename = "userEachUserListsLimit")]
    pub user_each_user_lists_limit: i32,
    #[serde(rename = "rateLimitFactor")]
    pub rate_limit_factor: i32,
    #[serde(rename = "avatarDecorationLimit")]
    pub avatar_decoration_limit: i32,
    #[serde(rename = "canImportAntennas")]
    pub can_import_antennas: bool,
    #[serde(rename = "canImportBlocking")]
    pub can_import_blocking: bool,
    #[serde(rename = "canImportFollowing")]
    pub can_import_following: bool,
    #[serde(rename = "canImportMuting")]
    pub can_import_muting: bool,
    #[serde(rename = "canImportUserLists")]
    pub can_import_user_lists: bool,
}

impl RolePolicies {
    pub fn new(gtl_available: bool, ltl_available: bool, can_public_note: bool, mention_limit: i32, can_invite: bool, invite_limit: i32, invite_limit_cycle: i32, invite_expiration_time: i32, can_manage_custom_emojis: bool, can_manage_avatar_decorations: bool, can_search_notes: bool, can_use_translator: bool, can_hide_ads: bool, drive_capacity_mb: i32, always_mark_nsfw: bool, can_update_bio_media: bool, pin_limit: i32, antenna_limit: i32, word_mute_limit: i32, webhook_limit: i32, clip_limit: i32, note_each_clips_limit: i32, user_list_limit: i32, user_each_user_lists_limit: i32, rate_limit_factor: i32, avatar_decoration_limit: i32, can_import_antennas: bool, can_import_blocking: bool, can_import_following: bool, can_import_muting: bool, can_import_user_lists: bool) -> RolePolicies {
        RolePolicies {
            gtl_available,
            ltl_available,
            can_public_note,
            mention_limit,
            can_invite,
            invite_limit,
            invite_limit_cycle,
            invite_expiration_time,
            can_manage_custom_emojis,
            can_manage_avatar_decorations,
            can_search_notes,
            can_use_translator,
            can_hide_ads,
            drive_capacity_mb,
            always_mark_nsfw,
            can_update_bio_media,
            pin_limit,
            antenna_limit,
            word_mute_limit,
            webhook_limit,
            clip_limit,
            note_each_clips_limit,
            user_list_limit,
            user_each_user_lists_limit,
            rate_limit_factor,
            avatar_decoration_limit,
            can_import_antennas,
            can_import_blocking,
            can_import_following,
            can_import_muting,
            can_import_user_lists,
        }
    }
}

