/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signin {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "headers")]
    pub headers: serde_json::Value,
    #[serde(rename = "success")]
    pub success: bool,
}

impl Signin {
    pub fn new(id: String, created_at: String, ip: String, headers: serde_json::Value, success: bool) -> Signin {
        Signin {
            id,
            created_at,
            ip,
            headers,
            success,
        }
    }
}

