/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersReportAbuseRequest {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "comment")]
    pub comment: String,
}

impl UsersReportAbuseRequest {
    pub fn new(user_id: String, comment: String) -> UsersReportAbuseRequest {
        UsersReportAbuseRequest {
            user_id,
            comment,
        }
    }
}

