/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersListsGetMemberships200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "user")]
    pub user: models::UserLite,
    #[serde(rename = "withReplies")]
    pub with_replies: bool,
}

impl UsersListsGetMemberships200ResponseInner {
    pub fn new(id: String, created_at: String, user_id: String, user: models::UserLite, with_replies: bool) -> UsersListsGetMemberships200ResponseInner {
        UsersListsGetMemberships200ResponseInner {
            id,
            created_at,
            user_id,
            user,
            with_replies,
        }
    }
}

