/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDetailedNotMe {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "username")]
    pub username: String,
    /// The local host is represented with `null`.
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "avatarUrl")]
    pub avatar_url: String,
    #[serde(rename = "avatarBlurhash")]
    pub avatar_blurhash: String,
    #[serde(rename = "avatarDecorations")]
    pub avatar_decorations: Vec<models::UserLiteAvatarDecorationsInner>,
    #[serde(rename = "isBot", skip_serializing_if = "Option::is_none")]
    pub is_bot: Option<bool>,
    #[serde(rename = "isCat", skip_serializing_if = "Option::is_none")]
    pub is_cat: Option<bool>,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<Box<models::UserLiteInstance>>,
    #[serde(rename = "emojis")]
    pub emojis: std::collections::HashMap<String, String>,
    #[serde(rename = "onlineStatus")]
    pub online_status: OnlineStatus,
    #[serde(rename = "badgeRoles", skip_serializing_if = "Option::is_none")]
    pub badge_roles: Option<Vec<models::UserLiteBadgeRolesInner>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "movedTo")]
    pub moved_to: String,
    #[serde(rename = "alsoKnownAs")]
    pub also_known_as: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastFetchedAt")]
    pub last_fetched_at: String,
    #[serde(rename = "bannerUrl")]
    pub banner_url: String,
    #[serde(rename = "bannerBlurhash")]
    pub banner_blurhash: String,
    #[serde(rename = "isLocked")]
    pub is_locked: bool,
    #[serde(rename = "isSilenced")]
    pub is_silenced: bool,
    #[serde(rename = "isSuspended")]
    pub is_suspended: bool,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "birthday")]
    pub birthday: String,
    #[serde(rename = "lang")]
    pub lang: String,
    #[serde(rename = "fields")]
    pub fields: Vec<models::IUpdateRequestFieldsInner>,
    #[serde(rename = "verifiedLinks")]
    pub verified_links: Vec<String>,
    #[serde(rename = "followersCount")]
    pub followers_count: f64,
    #[serde(rename = "followingCount")]
    pub following_count: f64,
    #[serde(rename = "notesCount")]
    pub notes_count: f64,
    #[serde(rename = "pinnedNoteIds")]
    pub pinned_note_ids: Vec<String>,
    #[serde(rename = "pinnedNotes")]
    pub pinned_notes: Vec<models::Note>,
    #[serde(rename = "pinnedPageId")]
    pub pinned_page_id: String,
    #[serde(rename = "pinnedPage")]
    pub pinned_page: Box<models::Page>,
    #[serde(rename = "publicReactions")]
    pub public_reactions: bool,
    #[serde(rename = "followingVisibility")]
    pub following_visibility: FollowingVisibility,
    #[serde(rename = "followersVisibility")]
    pub followers_visibility: FollowersVisibility,
    #[serde(rename = "twoFactorEnabled")]
    pub two_factor_enabled: bool,
    #[serde(rename = "usePasswordLessLogin")]
    pub use_password_less_login: bool,
    #[serde(rename = "securityKeys")]
    pub security_keys: bool,
    #[serde(rename = "roles")]
    pub roles: Vec<models::RoleLite>,
    #[serde(rename = "memo")]
    pub memo: String,
    #[serde(rename = "moderationNote", skip_serializing_if = "Option::is_none")]
    pub moderation_note: Option<String>,
    #[serde(rename = "isFollowing", skip_serializing_if = "Option::is_none")]
    pub is_following: Option<bool>,
    #[serde(rename = "isFollowed", skip_serializing_if = "Option::is_none")]
    pub is_followed: Option<bool>,
    #[serde(rename = "hasPendingFollowRequestFromYou", skip_serializing_if = "Option::is_none")]
    pub has_pending_follow_request_from_you: Option<bool>,
    #[serde(rename = "hasPendingFollowRequestToYou", skip_serializing_if = "Option::is_none")]
    pub has_pending_follow_request_to_you: Option<bool>,
    #[serde(rename = "isBlocking", skip_serializing_if = "Option::is_none")]
    pub is_blocking: Option<bool>,
    #[serde(rename = "isBlocked", skip_serializing_if = "Option::is_none")]
    pub is_blocked: Option<bool>,
    #[serde(rename = "isMuted", skip_serializing_if = "Option::is_none")]
    pub is_muted: Option<bool>,
    #[serde(rename = "isRenoteMuted", skip_serializing_if = "Option::is_none")]
    pub is_renote_muted: Option<bool>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<Notify>,
    #[serde(rename = "withReplies", skip_serializing_if = "Option::is_none")]
    pub with_replies: Option<bool>,
}

impl UserDetailedNotMe {
    pub fn new(id: String, name: String, username: String, host: String, avatar_url: String, avatar_blurhash: String, avatar_decorations: Vec<models::UserLiteAvatarDecorationsInner>, emojis: std::collections::HashMap<String, String>, online_status: OnlineStatus, url: String, uri: String, moved_to: String, also_known_as: Vec<String>, created_at: String, updated_at: String, last_fetched_at: String, banner_url: String, banner_blurhash: String, is_locked: bool, is_silenced: bool, is_suspended: bool, description: String, location: String, birthday: String, lang: String, fields: Vec<models::IUpdateRequestFieldsInner>, verified_links: Vec<String>, followers_count: f64, following_count: f64, notes_count: f64, pinned_note_ids: Vec<String>, pinned_notes: Vec<models::Note>, pinned_page_id: String, pinned_page: models::Page, public_reactions: bool, following_visibility: FollowingVisibility, followers_visibility: FollowersVisibility, two_factor_enabled: bool, use_password_less_login: bool, security_keys: bool, roles: Vec<models::RoleLite>, memo: String) -> UserDetailedNotMe {
        UserDetailedNotMe {
            id,
            name,
            username,
            host,
            avatar_url,
            avatar_blurhash,
            avatar_decorations,
            is_bot: None,
            is_cat: None,
            instance: None,
            emojis,
            online_status,
            badge_roles: None,
            url,
            uri,
            moved_to,
            also_known_as,
            created_at,
            updated_at,
            last_fetched_at,
            banner_url,
            banner_blurhash,
            is_locked,
            is_silenced,
            is_suspended,
            description,
            location,
            birthday,
            lang,
            fields,
            verified_links,
            followers_count,
            following_count,
            notes_count,
            pinned_note_ids,
            pinned_notes,
            pinned_page_id,
            pinned_page: Box::new(pinned_page),
            public_reactions,
            following_visibility,
            followers_visibility,
            two_factor_enabled,
            use_password_less_login,
            security_keys,
            roles,
            memo,
            moderation_note: None,
            is_following: None,
            is_followed: None,
            has_pending_follow_request_from_you: None,
            has_pending_follow_request_to_you: None,
            is_blocking: None,
            is_blocked: None,
            is_muted: None,
            is_renote_muted: None,
            notify: None,
            with_replies: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnlineStatus {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "offline")]
    Offline,
}

impl Default for OnlineStatus {
    fn default() -> OnlineStatus {
        Self::Unknown
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FollowingVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "followers")]
    Followers,
    #[serde(rename = "private")]
    Private,
}

impl Default for FollowingVisibility {
    fn default() -> FollowingVisibility {
        Self::Public
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FollowersVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "followers")]
    Followers,
    #[serde(rename = "private")]
    Private,
}

impl Default for FollowersVisibility {
    fn default() -> FollowersVisibility {
        Self::Public
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Notify {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "none")]
    None,
}

impl Default for Notify {
    fn default() -> Notify {
        Self::Normal
    }
}

