/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersAchievements200ResponseInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "unlockedAt")]
    pub unlocked_at: f64,
}

impl UsersAchievements200ResponseInner {
    pub fn new(name: String, unlocked_at: f64) -> UsersAchievements200ResponseInner {
        UsersAchievements200ResponseInner {
            name,
            unlocked_at,
        }
    }
}

