/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.9.0-alpha.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersRelationRequest {
    #[serde(rename = "userId")]
    pub user_id: Box<models::UsersRelationRequestUserId>,
}

impl UsersRelationRequest {
    pub fn new(user_id: models::UsersRelationRequestUserId) -> UsersRelationRequest {
        UsersRelationRequest {
            user_id: Box::new(user_id),
        }
    }
}

